/*
 * 
 *Created and built by @offensive #TDBSoft
 *
 */
package Student_MIS;

import java.sql.*;
import java.text.MessageFormat;
import javax.swing.JTable;
import java.awt.Component;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author paul.oamen
 */
public class StudentData extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst =null;
    ResultSet rs=null;
    DBconnection dbcon;
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form StudentData
     */
    public StudentData() {
        initComponents();
        Object col[] = {"StudentID","CourseCode","Maths","English","Biology","Computing","Chemistry","Physics", "Geography","Business","TotalScore", "Average","Ranking"};
        model.setColumnIdentifiers(col);
        jTable1.setModel(model);
        conn = dbcon.getConnection();
        updateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtStudentID = new javax.swing.JTextField();
        jtxtFirstname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtSurname = new javax.swing.JTextField();
        jcmbCourseCode = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jtxtTotalScore = new javax.swing.JTextField();
        jtxtAverage = new javax.swing.JTextField();
        jtxtRanking = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtxtMaths = new javax.swing.JTextField();
        jtxtBio = new javax.swing.JTextField();
        jtxtEng = new javax.swing.JTextField();
        jtxtChem = new javax.swing.JTextField();
        jtxtCom = new javax.swing.JTextField();
        jtxtBus = new javax.swing.JTextField();
        jtxtPhy = new javax.swing.JTextField();
        jtxtGeo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtTranscript = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtnupdateresult = new javax.swing.JButton();
        jbtnTranscript = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnRanking = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(176, 224, 230));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(176, 224, 230));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 12), "Student Record", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Student_ID:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jtxtStudentID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(jtxtStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 250, -1));

        jtxtFirstname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(jtxtFirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 250, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Firstname:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Surname:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jtxtSurname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(jtxtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 250, -1));

        jcmbCourseCode.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jcmbCourseCode.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "C98123", "C98234", "C98345", "C98567" }));
        jPanel2.add(jcmbCourseCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 250, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Course Code:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 420, 10));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Total Score:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jtxtTotalScore.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(jtxtTotalScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 250, -1));

        jtxtAverage.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(jtxtAverage, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 250, -1));

        jtxtRanking.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel2.add(jtxtRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 250, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Ranking:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Average:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Business:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Geography");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Physics:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Chemistry:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Computing:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Biology:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("English:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Maths:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, -1));

        jtxtMaths.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtMaths.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtMathsKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtMaths, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, 250, 40));

        jtxtBio.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtBio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBioKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtBio, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, 250, 40));

        jtxtEng.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtEng.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtEngKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtEng, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 250, 40));

        jtxtChem.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtChem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtChemKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtChem, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 250, 40));

        jtxtCom.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtCom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtComKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 250, 40));

        jtxtBus.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtBus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtBusKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtBus, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, 250, 40));

        jtxtPhy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtPhy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPhyKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtPhy, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 250, 40));

        jtxtGeo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtGeo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtGeoKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtGeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 250, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 910, 470));

        jPanel1.setBackground(new java.awt.Color(176, 224, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 12), "Transcript", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtTranscript.setColumns(20);
        jtxtTranscript.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jtxtTranscript.setRows(5);
        jScrollPane1.setViewportView(jtxtTranscript);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 380, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 420, 470));

        jTable1.setBackground(new java.awt.Color(176, 224, 230));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student_ID", "Course_Code", "Maths", "English", "Biology", "Computing", "Chemistry", "Physics", "Geo", "Business", "Total_Score", "Average", "Ranking"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 1330, 130));

        jbtnupdateresult.setBackground(new java.awt.Color(95, 158, 160));
        jbtnupdateresult.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jbtnupdateresult.setText("Update Result");
        jbtnupdateresult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnupdateresultActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnupdateresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 270, 40));

        jbtnTranscript.setBackground(new java.awt.Color(95, 158, 160));
        jbtnTranscript.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jbtnTranscript.setText("Transcript");
        jbtnTranscript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTranscriptActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnTranscript, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 610, -1, 40));

        jbtnDelete.setBackground(new java.awt.Color(95, 158, 160));
        jbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 610, 200, 40));

        jbtnReset.setBackground(new java.awt.Color(95, 158, 160));
        jbtnReset.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 610, 210, 40));

        jbtnExit.setBackground(new java.awt.Color(95, 158, 160));
        jbtnExit.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 610, 220, 40));

        jbtnPrint.setBackground(new java.awt.Color(95, 158, 160));
        jbtnPrint.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 610, 210, 40));

        jbtnRanking.setBackground(new java.awt.Color(95, 158, 160));
        jbtnRanking.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jbtnRanking.setText("Process Result");
        jbtnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRankingActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 270, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    
    private void jbtnupdateresultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnupdateresultActionPerformed
     
       double[] R = new double[14];
       R[0] = Double.parseDouble(jtxtMaths.getText());
       R[1] = Double.parseDouble(jtxtEng.getText());
       R[2] = Double.parseDouble(jtxtBio.getText());
       R[3] = Double.parseDouble(jtxtCom.getText());
       R[4] = Double.parseDouble(jtxtChem.getText());
       R[5] = Double.parseDouble(jtxtPhy.getText());
       R[6] = Double.parseDouble(jtxtGeo.getText());
       R[7] = Double.parseDouble(jtxtBus.getText());
       
       R[8] = (R[0] + R[1] + R[2] + R[3] + R[4] + R[5] + R[6] + R[7]) / 8;
       R[9] = R[0] + R[1] + R[2] + R[3] + R[4] + R[5] + R[6] + R[7];
       
       String Average = String.format("%.0f", R[8]);
       jtxtAverage.setText(Average);       
      
       String TotalScore = String.format("%.0f", R[9]);
       jtxtTotalScore.setText(TotalScore); 
       
       if (R[9] >= 700)
       {
           jtxtRanking.setText("First Class");
       }
       else if (R[9] >= 600)
       {
           jtxtRanking.setText("Second Class Upper");
       }
       else if (R[9] >= 500)
       {
           jtxtRanking.setText("Scond Class Lower");
       }
       else if (R[9] >= 400)
       {
           jtxtRanking.setText("Pass");
       }
       else if (R[9] >= 300)
       {
           jtxtRanking.setText("Pass");
       }
       else if (R[9] < 200)
       {
           jtxtRanking.setText("Fail");
       }
       //=================================Database===============================
    String sql="UPDATE `student` SET `CourseCode`=?,`Maths`=?,`English`=?,`Biology`=?,`Computing`=?,`Chemistry`=?,`Physics`=?,`Geography`=?,`Business`=?,`TotalScore`=?,`Average`=?,`Ranking`=? WHERE StudentID=?";
     
     try
     {
        pst = conn.prepareStatement(sql);
        pst.setString(1, (String) jcmbCourseCode.getSelectedItem());
        pst.setString(2, jtxtMaths.getText());
        pst.setString(3, jtxtEng.getText());
        pst.setString(4, jtxtBio.getText());
        pst.setString(5, jtxtCom.getText());
        pst.setString(6, jtxtChem.getText());
        pst.setString(7, jtxtPhy.getText());
        pst.setString(8, jtxtGeo.getText());
        pst.setString(9, jtxtBus.getText());
        pst.setString(10, jtxtTotalScore.getText());
        pst.setString(11, jtxtAverage.getText());
        pst.setString(12, jtxtRanking.getText());
        pst.setString(13, jtxtStudentID.getText());
        
        pst.execute();
         JOptionPane.showMessageDialog(null, "System Update Completed");
         
         rs.close();
         pst.close();      
        
        
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null,e);
     }
     updateTable();
    }//GEN-LAST:event_jbtnupdateresultActionPerformed

    private void jbtnTranscriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTranscriptActionPerformed
        jtxtTranscript.append("Student Result Recording Systems\n" 
                + "================================\n"
                + "Student ID:\t\t"+jtxtStudentID.getText()
                + "\nMaths:\t\t" + jtxtMaths.getText()
                + "\nEnglish:\t\t"+ jtxtEng.getText()
                + "\nBiology:\t\t"+ jtxtBio.getText()
                + "\nComputing:\t\t" + jtxtCom.getText()
                + "\nChemistry:\t\t" + jtxtChem.getText()
                + "\nPhysics:\t\t" + jtxtPhy.getText()
                + "\nAdd Maths:\t\t" + jtxtGeo.getText()
                + "\nBusiness:\t\t" + jtxtBus.getText()
                + "\n================================"
                + "\nTotal Score:\t\t" + jtxtTotalScore.getText()
                + "\nAverage:\t\t" + jtxtAverage.getText()
                + "\nRanking:\t\t" + jtxtRanking.getText()+"\n"
        );
        
    }//GEN-LAST:event_jbtnTranscriptActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        try{
            Connection con=dbcon.getConnection();
            PreparedStatement pr=con.prepareStatement("DELETE FROM `student` WHERE  StudentID='"+jtxtStudentID.getText()+"'");
            pr.executeUpdate();  
            updateTable();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e );
        }
        
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed

        JTextField temp=null;
        for(Component c:jPanel2.getComponents()){
            if(c.getClass().toString().contains("javax.swing.JTextField")){
                temp=(JTextField)c;
                temp.setText(null);
            }
        }
        jtxtTranscript.setText(null);
    }//GEN-LAST:event_jbtnResetActionPerformed
private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed

        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Student Result System",
            JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jtxtMathsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtMathsKeyTyped
         char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
            ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();       
    
    }
        
    }//GEN-LAST:event_jtxtMathsKeyTyped

    private void jtxtBioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBioKeyTyped
         char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
            ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();       
    
    }
    }//GEN-LAST:event_jtxtBioKeyTyped

    private void jtxtEngKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEngKeyTyped
         char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
            ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();       
    
    }
    }//GEN-LAST:event_jtxtEngKeyTyped

    private void jtxtChemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtChemKeyTyped
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
            ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();       
    
    }
    }//GEN-LAST:event_jtxtChemKeyTyped

    private void jtxtComKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtComKeyTyped
          char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
            ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();       
    
    }
    }//GEN-LAST:event_jtxtComKeyTyped

    private void jtxtBusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBusKeyTyped
      char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
            ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtBusKeyTyped

    private void jtxtPhyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPhyKeyTyped
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
            ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtPhyKeyTyped

    private void jtxtGeoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtGeoKeyTyped
        char iNumber = evt.getKeyChar();
        if(!(Character.isDigit(iNumber))
            ||(iNumber == KeyEvent.VK_BACK_SPACE)
            ||(iNumber == KeyEvent.VK_DELETE)){
            evt.consume();
        }
    }//GEN-LAST:event_jtxtGeoKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.getContentPane().setBackground(new java.awt.Color(176,224,230));
        
    }//GEN-LAST:event_formWindowActivated

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        MessageFormat header = new MessageFormat("Printing in progress");
            try
            {
            jtxtTranscript.print();      
            }
            catch (Exception e){
            System.err.format("No Printer found", e.getMessage());
            }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        
        jtxtStudentID.setText(RecordTable.getValueAt(SelectedRows, 0).toString());
        //txtFirstname.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        //txtSurname.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        jcmbCourseCode.setSelectedItem(RecordTable.getValueAt(SelectedRows, 1).toString());
        jtxtMaths.setText(RecordTable.getValueAt(SelectedRows, 2).toString());        
        jtxtEng.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        jtxtBio.setText(RecordTable.getValueAt(SelectedRows, 4).toString());        
        jtxtCom.setText(RecordTable.getValueAt(SelectedRows, 5).toString());          
        jtxtChem.setText(RecordTable.getValueAt(SelectedRows, 6).toString());        
        jtxtPhy.setText(RecordTable.getValueAt(SelectedRows, 7).toString());  
        jtxtGeo.setText(RecordTable.getValueAt(SelectedRows, 8).toString());  
        jtxtBus.setText(RecordTable.getValueAt(SelectedRows, 9).toString());  
        jtxtTotalScore.setText(RecordTable.getValueAt(SelectedRows, 10).toString());  
        jtxtAverage.setText(RecordTable.getValueAt(SelectedRows, 11).toString()); 
        jtxtRanking.setText(RecordTable.getValueAt(SelectedRows, 12).toString()); 
        //txtMobile.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
        
        
        //trnascript
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jbtnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRankingActionPerformed
        double[] R = new double[14];
       R[0] = Double.parseDouble(jtxtMaths.getText());
       R[1] = Double.parseDouble(jtxtEng.getText());
       R[2] = Double.parseDouble(jtxtBio.getText());
       R[3] = Double.parseDouble(jtxtCom.getText());
       R[4] = Double.parseDouble(jtxtChem.getText());
       R[5] = Double.parseDouble(jtxtPhy.getText());
       R[6] = Double.parseDouble(jtxtGeo.getText());
       R[7] = Double.parseDouble(jtxtBus.getText());
       
       R[8] = (R[0] + R[1] + R[2] + R[3] + R[4] + R[5] + R[6] + R[7]) / 8;
       R[9] = R[0] + R[1] + R[2] + R[3] + R[4] + R[5] + R[6] + R[7];
       
       String Average = String.format("%.0f", R[8]);
       jtxtAverage.setText(Average);       
      
       String TotalScore = String.format("%.0f", R[9]);
       jtxtTotalScore.setText(TotalScore); 
       
       if (R[9] >= 700)
       {
           jtxtRanking.setText("First Class");
       }
       else if (R[9] >= 600)
       {
           jtxtRanking.setText("Second Class Upper");
       }
       else if (R[9] >= 500)
       {
           jtxtRanking.setText("Scond Class Lower");
       }
       else if (R[9] >= 400)
       {
           jtxtRanking.setText("Pass");
       }
       else if (R[9] >= 300)
       {
           jtxtRanking.setText("Pass");
       }
       else if (R[9] < 200)
       {
           jtxtRanking.setText("Fail");
       }
       //=================================Database===============================
    String sql="INSERT INTO `student`(`StudentID`, `CourseCode`, `Maths`, `English`, `Biology`, `Computing`, `Chemistry`, `Physics`, `Geography`, `Business`, `TotalScore`, `Average`, `Ranking`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)";
     
     try
     {
        pst = conn.prepareStatement(sql);
        pst.setString(1, jtxtStudentID.getText());
        pst.setString(2, (String) jcmbCourseCode.getSelectedItem());
        pst.setString(3, jtxtMaths.getText());
        pst.setString(4, jtxtEng.getText());
        pst.setString(5, jtxtBio.getText());
        pst.setString(6, jtxtCom.getText());
        pst.setString(7, jtxtChem.getText());
        pst.setString(8, jtxtPhy.getText());
        pst.setString(9, jtxtGeo.getText());
        pst.setString(10, jtxtBus.getText());
        pst.setString(11, jtxtTotalScore.getText());
        pst.setString(12, jtxtAverage.getText());
        pst.setString(13, jtxtRanking.getText());
        
        pst.execute();
         JOptionPane.showMessageDialog(null, "System Update Completed");
         
         rs.close();
         pst.close();      
        
        
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(null,e);
     }
     updateTable();
    }//GEN-LAST:event_jbtnRankingActionPerformed

    /**
     * @param args the command line arguments
     */
 public void updateTable(){
  conn = dbcon.getConnection();
 String sql="Select StudentID,CourseCode,Maths,English,Biology,Computing,Chemistry,Physics,Geography,Business,TotalScore, Average,Ranking from Student";
 try{
    pst = conn.prepareStatement(sql);
    rs = pst.executeQuery();
    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(Exception e){
         JOptionPane.showMessageDialog(null,e);
     }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRanking;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTranscript;
    private javax.swing.JButton jbtnupdateresult;
    private javax.swing.JComboBox<String> jcmbCourseCode;
    private javax.swing.JTextField jtxtAverage;
    private javax.swing.JTextField jtxtBio;
    private javax.swing.JTextField jtxtBus;
    private javax.swing.JTextField jtxtChem;
    private javax.swing.JTextField jtxtCom;
    private javax.swing.JTextField jtxtEng;
    private javax.swing.JTextField jtxtFirstname;
    private javax.swing.JTextField jtxtGeo;
    private javax.swing.JTextField jtxtMaths;
    private javax.swing.JTextField jtxtPhy;
    private javax.swing.JTextField jtxtRanking;
    private javax.swing.JTextField jtxtStudentID;
    private javax.swing.JTextField jtxtSurname;
    private javax.swing.JTextField jtxtTotalScore;
    private javax.swing.JTextArea jtxtTranscript;
    // End of variables declaration//GEN-END:variables
}
